version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/hweeks
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
  deploy-sha:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t hweeks-circle --build-arg GIT_COMMIT=$(git log -1 --format=%h) .
          docker tag hweeks-circle hams/hweeks:$(git log -1 --format=%h)
          docker push hams/hweeks:$(git log -1 --format=%h)
          docker push hams/hweeks:latest
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/hweeks
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: |
          ssh-keyscan -H 206.189.222.25 >> ~/.ssh/known_hosts
          ssh root@206.189.222.25 'source ~/deploy.sh -n hweeks -i hams/hweeks:latest -p 3000:3000 -s hweeks.com -r http://hweeks:3000'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-sha
      - deploy:
          requires:
            - deploy-sha
          filters:
              branches:
                  only: master
