version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run: npm run ci
      # - run: mkdir aws
      # - run: ssh-keygen -b 2048 -t rsa -f aws/id_rsa -q -N ""
      - run: ls aws/
      - run: ssh-keyscan -H 34.210.133.207 >> ~/.ssh/known_hosts
      - run: ssh -o ec2-user@34.210.133.207
